package io.starter.happypath.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.stereotype.Controller;
@javax.annotation.Generated(value = "io.starter.ignite.generator.swagger.languages.StackGenSpringCodegen", date = "2020-04-14T12:17:28.197-07:00")

@Controller
/**
 CsatApi
 ############################## DO NOT EDIT: GENERATED FILE ##############################

    Generated by Starter StackGen: http://stackgen.io
    Powered by Swagger Codegen: http://swagger.io
    
    Template file: JavaSpring/apiController.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################
 
 StackGen Version: 
 
 */
public class CsatApiController implements CsatApi {

    
    @JsonIgnore
    @org.springframework.beans.factory.annotation.Autowired
    private CsatApiDelegate delegate = null;

	/**
	* No-Args Constructor for classloading.
	*/
	public CsatApiController() {
		// do not use
    }
    
    @org.springframework.beans.factory.annotation.Autowired
    public CsatApiController(CsatApiDelegate delegate) {
        this.delegate = delegate;
    }

    @JsonIgnore
    @Override
    public CsatApiDelegate getDelegate() {
        return delegate;
    }
}
